package com.woniu.pojo;
// Generated 2019-12-18 19:39:34 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clazz generated by hbm2java
 */
public class Clazz implements java.io.Serializable {

	private int cid;
	private Jieduan jieduan;
	private String cname;
	private String type;
	private Set students = new HashSet(0);

	public Clazz() {
	}

	public Clazz(int cid) {
		this.cid = cid;
	}

	public Clazz(int cid, Jieduan jieduan, String cname, String type, Set students) {
		this.cid = cid;
		this.jieduan = jieduan;
		this.cname = cname;
		this.type = type;
		this.students = students;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public Jieduan getJieduan() {
		return this.jieduan;
	}

	public void setJieduan(Jieduan jieduan) {
		this.jieduan = jieduan;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
